### PR TITLE
Fix YOLOX

### PR DESCRIPTION
**Pull request by Fleyderer**
This PR fixes known problems with YOLOX.

1) YOLOX can be used for tracking and evaluation
2) Metrics are almost the same as in original repo. ByteTrack yolox_m model `(MOTA, IDF1)` is `(87.0, 80.1)`, reproduced results are `(87.1, 79.9)`. 
Command for reproduce: 
```
python tracking/val.py --benchmark MOT17 --yolo-model yolox_m.pth --tracking-method bytetrack --reid-model osnet_x0_25_msmt17.pt --source tracking/val_utils/data/MOT17/train
```
3) Also provided new example for tracking
4) Added `imgsz` assignment for Ultralytics/YOLOX if parameter is not passed
5) Added `is_ultralytics_model` function to make it simple and without creating `ul_models` duplicates, which could lead to errors in future.

This PR can solve the following Issues:
#1600 
#1663 
#1422

### CODE REVIEW

**Comment by Fleyderer** [comment]
Strange thing, if I run this code, everything is just working without fails

**Comment by Fleyderer** [comment]
Ok, I'll try to find workaround. IMO it is better to add required packages to requirements instead of installing it on the fly after installing everything else, but no problem 🙂

**Comment by mikel-brostrom** [comment]
> Ok, I'll try to find workaround. IMO it is better to add required packages to requirements instead of installing it on the fly after installing everything else, but no problem 🙂

I agree, but the right strategy has to be imported anyways. So the pkg install I can fix after this merge 🚀

**Comment by mikel-brostrom** [comment]
You can use this for reference:

https://github.com/mikel-brostrom/boxmot/blob/755cb4d8045d335dbecf24a035b85719c1949688/tracking/track.py#L15

This is how it worked previously with `get_yolo_inferer`

**Comment by Fleyderer** [comment]
Yeah, it was not hard to change, but harder to find a way how to change it better to avoid problems in future.

Since `is_yolox_model` is now used in package installing and model selection, it will be fine 🙂

**Comment by Fleyderer** [comment]
This PR should also close #1740 
I have decided that this issue didn't deserve independent PR

**Comment by mikel-brostrom** [comment]
Looks good! 😄

**Pull request merged**
