### PR TITLE
Fix issue with missing arguments for centroid_batch function when using asso_func='centroid'

### PR DESCRIPTION
**Pull request by minicom365**
The centroid_batch function requires additional w and h arguments, unlike other IOU functions. However, in the current method, even when using the centroid method, only bboxes1 and bboxes2 are passed, resulting in an error.

#1372 
Error message: `TypeError: centroid_batch() missing 2 required positional arguments: 'w' and 'h'`

To resolve this issue, I have modified the method to correctly pass the w and h arguments to the centroid_batch function when the centroid method is used.

Changes made:

Added w and h arguments when calling the centroid_batch function.
This fix will resolve the error when using the centroid method.

Thank you.

### CODE REVIEW

**Review by brianlow — APPROVED** [review]

**Comment by mikel-brostrom** [comment]
Why was this closed? It makes sense 😄

**Comment by minicom365** [comment]
Sorry. This is my first time making a pull request, so I thought "approved these changes" meant it was completed.

**Comment by brianlow** [comment]
Thanks for this change. It fixed the problem for me

**Comment by brianlow** [comment]
I wonder if there is a fix that doesn't need an if statement. Seems like the caller shouldn't know about the particular type

I'm just a new user of this package though and am not familiar with the code

**Comment by minicom365** [comment]
The asso_func passed as an argument is processed in the __init__ method with self.asso_func = get_asso_func(asso_func) and then disappears as a local variable.

To implement it without using an if statement, the original asso_func should be stored within the class in the __init__ method.

**Comment by mikel-brostrom** [comment]
I believe the ultimate solution for his would be:

1. Extract w, h under update of each tracker

`h, w = img.shape[0:2]`

2. All tracker can then use `run_asso_func` function instead of `asso_func`. This is because `run_asso_func` takes an arbitrary amount of arguments adapting to the different association functions:

`run_asso_func(asso_func, detections, trackers, w, h)`

**Pull request closed without merging**
